### ISSUE TITLE
AnalyticsWindowsEditor.dll in Linux editor

### ISSUE THREAD

**Issue by DimaPetrinko** [devtodev-analytics/package_Analytics#1]
Hello, recently i encountered a problem with this package on Linux
Unity editor seemingly is unable to load some dll. After two days of digging i found out that the dll that the editor cannot load is AnalyticsWindowsEditor.dll. After inspecting it i noticed that the OS requirement was set to specifically Windows. After i changed the option to Any OS the errors were gone
I would greatly appreciate if you fix this minor issue with major consequences (at least for such a hipster like me:))

**Comment by tg-roshiroku** [comment]
Any plans to implement linux support?

**Comment by kaikristo** [comment]
Yes, we planning to release lunux support for editor soon.

**Comment by kaikristo** [comment]
https://github.com/devtodev-analytics/package_Analytics/releases/tag/v3.8.0
