### ISSUE TITLE
namespace Assets.* can conflict with the popular class name "Assets"

### ISSUE THREAD

**Issue by rzer** [devtodev-analytics/package_Analytics#2]
It's not a bug, but extra work after adding package to a project.

**Comment by Wainakh** [comment]
I agree with the author. This package simply takes that name without even using it. We have a large-scale framework, divided into several packages, used in many projects, which also uses the name “Assets”, but for its intended purpose.

**Comment by kaikristo** [comment]
fixed in v.3.7.0
