### ISSUE TITLE
Unnecessary MacOSUnity File in Resources

### ISSUE THREAD

**Issue by ozeecode** [devtodev-analytics/package_Analytics#6]
I am not sure what purpose this file serves, but I believe it is not used in Android builds. Since the file is located in the Resources folder, it is included in every build, increasing the build size by an extra 21mb.

![Screenshot 2024-02-11 220014](https://github.com/devtodev-analytics/package_Analytics/assets/3259983/e80e6fec-2ca3-4919-8bfa-4892d2b79192)

![Screenshot 2024-02-11 220425](https://github.com/devtodev-analytics/package_Analytics/assets/3259983/16986a61-3609-448e-9a5f-01b219645af9)

Note: I removed the MacOSUnity file and the Android build worked perfectly fine.

**Comment by kaikristo** [comment]
fixed in v3.8.0
