### ISSUE TITLE
Multiple precompiled assemblies with the same name

### ISSUE THREAD

**Issue by kroer** [devtodev-analytics/package_Analytics#8]
After integration, devtodev starts conflicting with Xsolla.

`
Multiple precompiled assemblies with the same name System.Runtime.CompilerServices.Unsafe.dll included or the current platform. Only one assembly with the same name is allowed per platform.
`

Conflict in three assemblies System.Runtime.CompilerServices.Unsafe, System.Memory and System.Buffers.

I tried to exclude these assemblies from the editor in import settings. But start appears errors about version mismatch.

`
Assembly 'Assets/Xsolla/Core/Browser/XsollaBrowser/Plugins/Microsoft.Net.Http.Headers.dll' will not be loaded due to errors:
Microsoft.Net.Http.Headers references strong named System.Buffers Assembly references: 4.0.2.0 Found in project: 4.0.3.0.
`

Is there any solution?

**Comment by kaikristo** [comment]
1. Download devtodev sdk from our git repository. https://github.com/devtodev-analytics/Unity-sdk-3.0
2. Remove all conflicting dlls from the folder Assets/Plugins/DevToDev/Analytics/Windows/Dependencies (System.Buffers.dll, System.Memory.dll, System.Numerics.Vectors.dll, System.Runtime.CompilerServices.Unsafe.dll)

**Comment by kroer** [comment]
Thanks a lot.
